### ISSUE TITLE
Rig 8ball

### ISSUE THREAD

**Issue by fishy15** [frodakcin/orz-bot#6]
Does anybody have any ideas for what we can add to rig the 8ball?

I was thinking something like this:

```py
if 'eyg' in message and 'pedo' in message:
    answer = 'eyg is a pedo'
```

or something like that.

**Comment by aryamanarora** [comment]
Okay, I will implement that. But we also need something about `'fishy'` and `'geniosity'` as well.

**Comment by aryamanarora** [comment]
Done 😎
